# Generated by Django 3.0.3 on 2020-03-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200304_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Image'),
        ),
    ]
